# Generated by Django 2.1.1 on 2018-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20180924_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
